name: medicall_pro
description: "MediCall Pro — Application professionnelle d'appel de patients pour hôpitaux."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Design & Icônes
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10

  # Gestion d'état
  flutter_riverpod: ^2.5.1

  # Base de données & Temps réel
  supabase_flutter: ^2.5.6

  # Synthèse vocale
  flutter_tts: ^4.0.2

  # Utilitaires
  intl: ^0.19.0
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  connectivity_plus: ^6.0.5
  sqflite: ^2.3.3+1
  path: ^1.9.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
